### ISSUE TITLE
Animation is not displayed HUAWEI MATE 9 EMUI

### ISSUE THREAD

**Issue by giancafigueroa** [krtkush/LinearTimer#34]
The animation component is not shown, if it indicates the space it occupies but does not show the animation.

I only spend that in HUAWEI MATE 9 EMUI

**Comment by krtkush** [comment]
Unfortunately, I don't have a HUAWEI device to replicate this bug.

Could you please upload a a screen capture (video/ pic) of what is going wrong?

**Comment by giancafigueroa** [comment]
give me your email to send you the videos

**Comment by krtkush** [comment]
Please upload it here, in public, and post the url as a comment for documentation purposes - 

https://gfycat.com/upload

**Comment by giancafigueroa** [comment]
https://gfycat.com/GentlePinkGreendarnerdragonfly

**Comment by giancafigueroa** [comment]
https://gfycat.com/TestyUncomfortableIsopod

**Comment by krtkush** [comment]
Hey,

Thanks for uploading the video.

I see nothing wrong with the animation. It's working as shown in the gif on
the read me -

https://raw.githubusercontent.com/krtkush/LinearTimer/master/Screenshots/demo.gif

Perhaps you could explain your exact requirement, I'll try to help you out.

On 15-Jun-2018 at 6:22 PM, <gianca970226 <notifications@github.com>> wrote:

https://gfycat.com/GentlePinkGreendarnerdragonfly

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/krtkush/LinearTimer/issues/34#issuecomment-397610817>,
or mute the thread

**Comment by giancafigueroa** [comment]
It is that I sent you two comparisons that in the other devices works well but in the huawei shows us

**Comment by krtkush** [comment]
Aah! Okay. I did not see the other gif. I see the problem now.

I'll try to figure this out.

Thanks for reporting.


On 15-Jun-2018 at 8:50 PM, <gianca970226 <notifications@github.com>> wrote:

It is that I sent you two comparisons that in the other devices works well
but in the huawei shows us

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/krtkush/LinearTimer/issues/34#issuecomment-397655244>,
or mute the thread

**Comment by giancafigueroa** [comment]
Clarification, I do not know why I installed the app you have in the play store and it shows well in that Hauwei I do not know what I can have wrong in the impementacion but it works on many devices in that is the only one that is not shown in my app

**Comment by krtkush** [comment]
Cool. I'll keep that in mind.

Also, meanwhile, you can maybe clone this repo and check if that works or
not.


On 15-Jun-2018 at 9:02 PM, <gianca970226 <notifications@github.com>> wrote:

Clarification, I do not know why I installed the app you have in the play
store and it shows well in that Hauwei I do not know what I can have wrong
in the impementacion but it works on many devices in that is the only one
that is not shown in my app

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/krtkush/LinearTimer/issues/34#issuecomment-397658756>,
or mute the thread

**Comment by krtkush** [comment]
Not reproducible.
